// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnDgAksq-ztcCRQZVxUB5-0beypXnkkNg',
    appId: '1:259122812284:web:48f5f2837567926e6440f9',
    messagingSenderId: '259122812284',
    projectId: 'habitsapp-27907',
    authDomain: 'habitsapp-27907.firebaseapp.com',
    storageBucket: 'habitsapp-27907.firebasestorage.app',
    measurementId: 'G-70FWEMXMZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNattD5ALxaqt5hxq7oNh_eRrDZ1E0a6Q',
    appId: '1:259122812284:android:622e7d630c5daf216440f9',
    messagingSenderId: '259122812284',
    projectId: 'habitsapp-27907',
    storageBucket: 'habitsapp-27907.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ6ekzHHtgxFbiXkDVQ2tYID51R_5NlKk',
    appId: '1:259122812284:ios:7d2833d85f721a9c6440f9',
    messagingSenderId: '259122812284',
    projectId: 'habitsapp-27907',
    storageBucket: 'habitsapp-27907.firebasestorage.app',
    iosBundleId: 'com.example.habitsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ6ekzHHtgxFbiXkDVQ2tYID51R_5NlKk',
    appId: '1:259122812284:ios:7d2833d85f721a9c6440f9',
    messagingSenderId: '259122812284',
    projectId: 'habitsapp-27907',
    storageBucket: 'habitsapp-27907.firebasestorage.app',
    iosBundleId: 'com.example.habitsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnDgAksq-ztcCRQZVxUB5-0beypXnkkNg',
    appId: '1:259122812284:web:ee87ee974a307d686440f9',
    messagingSenderId: '259122812284',
    projectId: 'habitsapp-27907',
    authDomain: 'habitsapp-27907.firebaseapp.com',
    storageBucket: 'habitsapp-27907.firebasestorage.app',
    measurementId: 'G-DEJ265KN7S',
  );
}
